### ISSUE TITLE
Problems on Ubuntu 20.04

### ISSUE THREAD

**Issue by Vertexwahn** [zaucy/rules_blender#19]
I tested the rules on Ubunutu 20.04 and ran into the following problem (on macOS 10.15 and Windows 10 it works without any problems):

```
$ bazel test //example:example
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //example:example (40 packages loaded, 156 targets configured).
INFO: Found 1 target and 0 test targets...
ERROR: /home/vertexwahn/dev/rules_blender/example/BUILD.bazel:3:15: Rendering 'example/example.blend' frame 0 failed: IOException while preparing the execution environment of a worker:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Cannot run program "/home/vertexwahn/.cache/bazel/_bazel_vertexwahn/2ad5c946bda9b24b85dfc716d93b4dc2/execroot/rules_blender/bazel-out/host/bin/external/blender/blender" (in directory "/home/vertexwahn/.cache/bazel/_bazel_vertexwahn/2ad5c946bda9b24b85dfc716d93b4dc2/execroot/rules_blender"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.google.devtools.build.lib.shell.JavaSubprocessFactory.start(JavaSubprocessFactory.java:147)
	at com.google.devtools.build.lib.shell.JavaSubprocessFactory.create(JavaSubprocessFactory.java:169)
	at com.google.devtools.build.lib.shell.SubprocessBuilder.start(SubprocessBuilder.java:230)
	at com.google.devtools.build.lib.worker.WorkerMultiplexer.createProcess(WorkerMultiplexer.java:159)
	at com.google.devtools.build.lib.worker.WorkerProxy.prepareExecution(WorkerProxy.java:59)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:402)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:209)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:245)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:146)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:328)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 30 more
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /home/vertexwahn/.cache/bazel/_bazel_vertexwahn/2ad5c946bda9b24b85dfc716d93b4dc2/bazel-workers/multiplex-worker-1-BlenderRender.log ---8<---8<---
(empty)
---8<---8<--- End of log ---8<---8<---
Target //example:example failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.270s, Critical Path: 0.05s
INFO: 6 processes: 6 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```

**Comment by zaucy** [comment]
I haven't been able to reproduce this. I'm closing for now, but feel free to re-open!
